# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
# run locally with act: bin/act -j test
name: "Ruby on Rails CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@master
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: "100.0.4896.20"

      - name: Debug Chrome Path
        run: |
          echo "Checking common chrome paths..."
          ls -l /usr/local/bin/google-chrome || echo "Not found in /usr/local/bin/google-chrome"
          ls -l /usr/bin/google-chrome || echo "Not found in /usr/bin/google-chrome"
          ls -l /opt/google/chrome/google-chrome || echo "Not found in /opt/google/chrome/google-chrome"
          which chrome || echo "Chrome binary not found in PATH"
      - name: Add Chrome to PATH
        run: echo "/usr/bin" >> $GITHUB_PATH
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      # Add or replace database setup steps here
      #- name: Set up database schema
      #  run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Install CodeClimate test reporter
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - name: Make test reporter executable
        run: chmod +x ./cc-test-reporter
      - name: Run CodeClimate test reporter before tests
        run: ./cc-test-reporter before-build
      - name: Run tests with coverage
        run: bundle exec rspec
      - name: Upload coverage to CodeClimate
        run: ./cc-test-reporter after-build --exit-code $?

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --parallel
  #    - name: Generate binstubs
  #      run: bundle binstubs bundler-audit brakeman rubocop
  #    # Add or replace any other lints here
  #    - name: Security audit dependencies
  #      run: bin/bundler-audit --update
  #    - name: Security audit application code
  #      run: bin/brakeman -q -w2
  #    - name: Lint Ruby files
  #     run: bin/rubocop --parallel
